logo:
  src: /logo-active.svg
  show_in_header: true

backend:
  name: github
  repo: FSC-Racing-Team/FSCSite-2.0
  branch: gh-pages
  base_url: https://fscracing-decap-proxy.fsc-generale.workers.dev
  auth_endpoint: /auth

media_folder: "dev/assets/uploads"
public_folder: "/dev/assets/uploads"

collections:
  - name: "team"
    label: "Team (DEV)"
    files:
      - label: "Persone"
        name: "members"
        file: "dev/data/members.json"
        format: "json"
        fields:
          - label: "Membri"
            name: "members"
            widget: "list"
            summary: "{{fields.dept}} / {{fields.unit}} â€” {{fields.name}}"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Ruolo", name: "role", widget: "string" }

              - label: "Reparto (pagina)"
                name: "dept"
                widget: "select"
                options:
                  - { label: "Management", value: "management" }
                  - { label: "Elettrica", value: "elettrica" }
                  - { label: "Meccanica", value: "meccanica" }

              - label: "Sottoreparto"
                name: "unit"
                widget: "select"
                options:
                  - { label: "Management", value: "management" }
                  - { label: "Professori", value: "professori" }
                  - { label: "Low Voltage", value: "low_voltage" }
                  - { label: "High Voltage", value: "high_voltage" }
                  - { label: "Vehicle Dynamics", value: "vehicle_dynamics" }
                  - { label: "Aerodinamica", value: "aerodynamics" }
                  - { label: "Mechanical Design", value: "mechanical_design" }

              - { label: "Bio (opzionale)", name: "bio", widget: "text", required: false }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "Capo reparto (special)", name: "special", widget: "boolean", default: false, required: false }
              - { label: "Foto", name: "photo", widget: "image", required: false }

              - { label: "Visibile", name: "visible", widget: "boolean", default: true, required: false }
              - { label: "Ordine", name: "order", widget: "number", default: 0, required: false }
